const DATA={
hiragana:{name:"Hiragana",lessons:[
{title:"A Row",cards:[["あ","a"],["い","i"],["う","u"],["え","e"],["お","o"]]},
{title:"K Row",cards:[["か","ka"],["き","ki"],["く","ku"],["け","ke"],["こ","ko"]]},
{title:"S Row",cards:[["さ","sa"],["し","shi"],["す","su"],["せ","se"],["そ","so"]]},
{title:"T Row",cards:[["た","ta"],["ち","chi"],["つ","tsu"],["て","te"],["と","to"]]},
{title:"N Row",cards:[["な","na"],["に","ni"],["ぬ","nu"],["ね","ne"],["の","no"]]},
{title:"H Row",cards:[["は","ha"],["ひ","hi"],["ふ","fu"],["へ","he"],["ほ","ho"]]},
{title:"M Row",cards:[["ま","ma"],["み","mi"],["む","mu"],["め","me"],["も","mo"]]},
{title:"Y Row",cards:[["や","ya"],["ゆ","yu"],["よ","yo"]]},
{title:"R Row",cards:[["ら","ra"],["り","ri"],["る","ru"],["れ","re"],["ろ","ro"]]},
{title:"W + N",cards:[["わ","wa"],["を","wo/o"],["ん","n"]]}]},
katakana:{name:"Katakana",lessons:[
{title:"A Row",cards:[["ア","a"],["イ","i"],["ウ","u"],["エ","e"],["オ","o"]]},
{title:"K Row",cards:[["カ","ka"],["キ","ki"],["ク","ku"],["ケ","ke"],["コ","ko"]]},
{title:"S Row",cards:[["サ","sa"],["シ","shi"],["ス","su"],["セ","se"],["ソ","so"]]},
{title:"T Row",cards:[["タ","ta"],["チ","chi"],["ツ","tsu"],["テ","te"],["ト","to"]]},
{title:"N Row",cards:[["ナ","na"],["ニ","ni"],["ヌ","nu"],["ネ","ne"],["ノ","no"]]},
{title:"H Row",cards:[["ハ","ha"],["ヒ","hi"],["フ","fu"],["ヘ","he"],["ホ","ho"]]},
{title:"M Row",cards:[["マ","ma"],["ミ","mi"],["ム","mu"],["メ","me"],["モ","mo"]]},
{title:"Y Row",cards:[["ヤ","ya"],["ユ","yu"],["ヨ","yo"]]},
{title:"R Row",cards:[["ラ","ra"],["リ","ri"],["ル","ru"],["レ","re"],["ロ","ro"]]},
{title:"W + N",cards:[["ワ","wa"],["ヲ","wo/o"],["ン","n"]]}]},
kanji:{name:"Kanji",lessons:[
{title:"N5 Set 1",cards:[["日","sun/day | nichi, jitsu, hi"],["月","moon/month | getsu, gatsu, tsuki"],["火","fire | ka, hi"],["水","water | sui, mizu"],["木","tree/wood | moku, ki"]]},
{title:"N5 Set 2",cards:[["金","gold/money | kin, kane"],["土","earth/soil | do, tsuchi"],["人","person | jin, hito"],["口","mouth | kou, kuchi"],["目","eye | moku, me"]]},
{title:"N5 Set 3",cards:[["山","mountain | san, yama"],["川","river | sen, kawa"],["田","rice field | den, ta"],["力","power | riki, chikara"],["女","woman | jo, onna"]]}]}};
let subject="hiragana",lessonType="new",selected={subject:"hiragana",title:"",cards:[]},deck=[],modes=[],mode="flash",idx=0,revealed=false,answered=false,traceOn=false;
let stats=JSON.parse(localStorage.getItem("stats")||"{}"),mastery=JSON.parse(localStorage.getItem("mastery")||"{}"),missed=JSON.parse(localStorage.getItem("missed")||"[]");
let drawing=false,ctx=null;
function id(c,s=selected.subject){return s+"|"+c[0]+"|"+c[1]}function save(){localStorage.setItem("stats",JSON.stringify(stats));localStorage.setItem("mastery",JSON.stringify(mastery));localStorage.setItem("missed",JSON.stringify(missed))}
function show(x){document.querySelectorAll(".screen").forEach(e=>e.classList.remove("active"));document.getElementById(x).classList.add("active");if(x==="home")coachText.textContent=coach();if(x==="study"&&mode==="draw")setTimeout(setupCanvas,50)}
function getM(c,s=selected.subject){let k=id(c,s);return mastery[k]??30}function setM(c,ok){let k=id(c);let d=ok?8:-15;if(ok&&mode==="draw")d+=5;if(ok&&mode==="multi")d+=2;if(!ok&&mode==="draw")d-=3;mastery[k]=Math.max(0,Math.min(100,(mastery[k]??30)+d));save()}
function allCards(s=subject,n=null){let arr=[];DATA[s].lessons.forEach((l,i)=>{if(n===null||i<=n)arr=arr.concat(l.cards)});return arr}
function selectSubject(s){if(s==="missed"){selected={subject:"missed",title:"Global Missed Set",cards:missed.map(x=>[x.f,x.b])};openPreview();return}subject=s;lessonType="new";renderLessons();show("lessons")}
function showLessonType(t){lessonType=t;renderLessons()}
function avg(cards,s=subject){if(!cards.length)return 0;return Math.round(cards.map(c=>getM(c,s)).reduce((a,b)=>a+b,0)/cards.length)}
function renderLessons(){subjectTitle.textContent=DATA[subject].name+" Learning Path";tabNew.classList.toggle("activeTab",lessonType==="new");tabCum.classList.toggle("activeTab",lessonType==="cumulative");lessonList.innerHTML="";DATA[subject].lessons.forEach((l,i)=>{let cards=lessonType==="new"?l.cards:allCards(subject,i);let m=avg(cards,subject);let div=document.createElement("div");div.className="panel lesson";div.onclick=()=>{selected={subject,title:(lessonType==="new"?l.title:"Cumulative through "+l.title),cards};openPreview()};div.innerHTML=`<div class="status">${m>=90?"✅":m>=70?"🟣":"⭕"}</div><div><strong>Lesson ${i+1}: ${lessonType==="new"?l.title:"Review 1-"+(i+1)}</strong><p>${cards.map(c=>c[0]).join(" ")}</p><div class="bar"><div class="fill" style="width:${m}%"></div></div></div><div>${m}%</div>`;lessonList.appendChild(div)})}
function openPreview(){previewTitle.textContent=selected.title;previewText.textContent=selected.subject==="missed"?"These are cards you missed across all subjects.":`This set has ${selected.cards.length} cards. Drago Session will mix flashcards, multiple choice, and drawing.`;previewCards.innerHTML="";selected.cards.forEach(c=>{let d=document.createElement("div");d.innerHTML=`<div class="kana">${c[0]}</div><div>${c[1]}</div><div class="small">${getM(c,selected.subject)}%</div>`;previewCards.appendChild(d)});show("preview")}
function startDragoSession(){deck=buildMixedDeck(selected.cards);idx=0;revealed=false;show("study");update()}
function buildMixedDeck(cards){let session=[];cards.forEach(c=>{let m=getM(c,selected.subject);let reps=m<50?3:m<80?2:1;for(let i=0;i<reps;i++){session.push({card:c,mode:i%3===0?"flash":i%3===1?"multi":"draw"})}});return session.sort(()=>Math.random()-.5)}
function startRecommended(){subject="hiragana";let weak=allCards("hiragana").filter(c=>getM(c,"hiragana")<70);selected={subject:"hiragana",title:"Adaptive Hiragana Drago Session",cards:weak.length?weak:allCards("hiragana",7)};startDragoSession()}
function update(){if(!deck.length){progress.textContent="No cards.";front.textContent="✓";back.textContent="";return}if(idx>=deck.length)idx=0;let item=deck[idx],c=item.card;mode=item.mode;studyTitle.textContent=selected.title+" - Drago Session";sessionType.textContent=mode==="flash"?"🎴 Flashcard":mode==="multi"?"🎯 Multiple Choice":"✍️ Drawing";flashArea.style.display=mode==="flash"?"block":"none";multiArea.style.display=mode==="multi"?"block":"none";drawArea.style.display=mode==="draw"?"block":"none";if(mode==="flash"){front.textContent=c[0];back.textContent=c[1];back.style.display=revealed?"block":"none"}else if(mode==="multi"){buildMC(c)}else{drawTarget.textContent="Draw: "+c[1].split("|")[0].trim();drawAnswer.textContent="Answer: "+c[0];traceChar.textContent=c[0];traceChar.classList.toggle("off",!traceOn);if(document.getElementById("traceBtn"))traceBtn.textContent=traceOn?"Hide Trace Guide":"Show Trace Guide";drawAnswer.style.display="none";setTimeout(()=>{setupCanvas();clearCanvas()},50)}progress.textContent=`Step ${idx+1} of ${deck.length} | Mastery: ${Math.round(getM(c,selected.subject))}% | Missed: ${missed.length}`}
function flip(){if(mode==="flash"){revealed=!revealed;update()}}function next(){if(!deck.length)return;idx=(idx+1)%deck.length;revealed=false;answered=false;update()}function prev(){if(!deck.length)return;idx=(idx-1+deck.length)%deck.length;revealed=false;answered=false;update()}function shuffleDeck(){deck.sort(()=>Math.random()-.5);idx=0;update()}
function record(c,ok){let k=id(c);if(!stats[k])stats[k]={seen:0,correct:0,missed:0};stats[k].seen++;ok?stats[k].correct++:stats[k].missed++;setM(c,ok);if(!ok&&!missed.some(x=>x.k===k))missed.push({k,f:c[0],b:c[1]});if(ok&&getM(c,selected.subject)>=75)missed=missed.filter(x=>x.k!==k);save()}
function grade(ok){record(deck[idx].card,ok);next()}
function buildMC(c){answered=false;mcQ.textContent=c[0];mcFeed.textContent="";let pool=allCards(selected.subject==="missed"?subject:selected.subject).filter(x=>x[0]!==c[0]);let choices=[c];while(choices.length<4&&pool.length)choices.push(pool.splice(Math.floor(Math.random()*pool.length),1)[0]);choices.sort(()=>Math.random()-.5);let box=document.getElementById("choices");box.innerHTML="";choices.forEach(ch=>{let b=document.createElement("button");b.className="choice";b.textContent=ch[1];b.onclick=()=>answerMC(b,ch,c);box.appendChild(b)})}
function answerMC(b,ch,c){if(answered)return;answered=true;document.querySelectorAll(".choice").forEach(x=>{if(x.textContent===c[1])x.classList.add("correct")});let ok=ch[1]===c[1];record(c,ok);if(!ok)b.classList.add("wrong");mcFeed.textContent=ok?"Correct.":`Missed it. ${c[0]} = ${c[1]}`;setTimeout(next,900)}
function setupCanvas(){let canvas=document.getElementById("drawCanvas");if(!canvas)return;let rect=canvas.getBoundingClientRect();canvas.width=rect.width*devicePixelRatio;canvas.height=rect.height*devicePixelRatio;ctx=canvas.getContext("2d");ctx.scale(devicePixelRatio,devicePixelRatio);ctx.lineWidth=8;ctx.lineCap="round";ctx.strokeStyle="#7c3aed";canvas.onpointerdown=e=>{drawing=true;ctx.beginPath();ctx.moveTo(e.offsetX,e.offsetY)};canvas.onpointermove=e=>{if(!drawing)return;ctx.lineTo(e.offsetX,e.offsetY);ctx.stroke()};canvas.onpointerup=()=>drawing=false;canvas.onpointerleave=()=>drawing=false}
function clearCanvas(){let canvas=document.getElementById("drawCanvas");if(ctx&&canvas){ctx.clearRect(0,0,canvas.width,canvas.height)}}function toggleDrawAnswer(){drawAnswer.style.display=drawAnswer.style.display==="none"?"block":"none"}function toggleTrace(){traceOn=!traceOn;traceChar.classList.toggle("off",!traceOn);if(document.getElementById("traceBtn"))traceBtn.textContent=traceOn?"Hide Trace Guide":"Show Trace Guide"}
function showDash(){dashTitle.textContent=(selected.title||DATA[subject].name)+" Dashboard";let cards=selected.cards.length?selected.cards:allCards(subject);let ssub=selected.subject||subject,total=0,correct=0;cards.forEach(c=>{let s=stats[id(c,ssub)]||{seen:0,correct:0};total+=s.seen;correct+=s.correct});totalQ.textContent=total;acc.textContent=total?Math.round(correct/total*100)+"%":"0%";avgM.textContent=avg(cards,ssub)+"%";missedN.textContent=missed.length;let weakCards=cards.filter(c=>getM(c,ssub)<70).sort((a,b)=>getM(a,ssub)-getM(b,ssub));analysis.textContent=weakCards.length?`Drago says: focus on ${weakCards.slice(0,3).map(c=>c[0]).join(", ")} before adding more.`:"Drago says: strong set. Move to cumulative review or the next lesson.";weak.innerHTML="";weakCards.slice(0,10).forEach(c=>{let p=document.createElement("span");p.className="pill";p.textContent=`${c[0]} = ${c[1]} (${getM(c,ssub)}%)`;weak.appendChild(p)});masteryList.innerHTML="";cards.forEach(c=>{let m=getM(c,ssub);let row=document.createElement("div");row.className="mastery-item";row.innerHTML=`<strong>${c[0]}</strong><div class="bar"><div class="fill" style="width:${m}%"></div></div><span>${m}%</span>`;masteryList.appendChild(row)});show("dashboard")}
function coach(){let h=avg(allCards("hiragana",7),"hiragana");return h<80?"Drago says: try drawing from memory first. Tap Show Trace Guide only when you need help.":"Drago says: you're ready for cumulative review or the next set."}
function resetAll(){if(confirm("Reset all DragoLearn progress?")){stats={};mastery={};missed=[];save();showDash()}}
if("serviceWorker"in navigator)navigator.serviceWorker.register("service-worker.js");coachText.textContent=coach();